server:
  port: 8080
  forward-headers-strategy: framework
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto
      remote-ip-header: x-forwarded-for

spring:
  application:
    name: incheon_mate-backend


  #  Spring Boot 4.x Mongo 설정 (deprecated 아님)
  mongodb:
    uri: mongodb://${DB_HOST:localhost}:27017/incheon_mate_db
    #uri: mongodb://${DB_HOST:mongodb}:27017/incheon_mate_db



  data:
    mongodb:
      auto-index-creation: true
    #  Redis는 spring.data.redis 아래가 정석
    redis:
      #host: ${REDIS_HOST:redis}
      host: ${REDIS_HOST:localhost}
      port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "https://localhost:8080/login/oauth2/code/google"
            client-name: Google

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: "https://triggerless-battlesome-teodoro.ngrok-free.dev/auth/kakao/callback"
  api:
    key: ${KAKAO_KEY}


jwt:
  #secret: ${JWT_SECRET:vladimir_putin_is_not_my_president_just_a_random_long_secret_key_for_dev}
  secret: ${JWT_SECRET}
  #JWT_SECRET=VGhpc0lzQVRlc3RTZWNyZXRLZXlGb3JKd3RFeGFtcGxlV2hpY2hJc0xvbmdFbm91Z2hUb0F2b2lkV2Vha0tleUV4Y2VwdGlvbg==


app:
  frontend:
    redirect-url: "https://2025-capstone-design-fe.vercel.app/oauth/callback"




springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

#com.example.IncheonMate만 로깅 레벨을 Debug로 조정
logging:
  level:
    root: INFO
    com.example.IncheonMate: DEBUG



