server:
  port: 8080

spring:
  application:
    name: incheon_mate-backend

  #  Spring Boot 4.x Mongo 설정 (deprecated 아님)
  mongodb:
    uri: mongodb://${DB_HOST:mongodb}:27017/incheon_mate_db


  data:
    mongodb:
      auto-index-creation: true
    #  Redis는 spring.data.redis 아래가 정석
    redis:
      host: ${REDIS_HOST:redis}
      port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            client-name: Google

jwt:
  secret: ${JWT_SECRET:vladimir_putin_is_not_my_president_just_a_random_long_secret_key_for_dev}


app:
  frontend:
    redirect-url: http://localhost:3000/oauth/callback
